version: 2.1
orbs:
  node: circleci/node@4.0.1
  heroku: circleci/heroku@1.2.2
jobs:
  test:
    docker:
      - image: 'cimg/base:stable'
    working_directory: ~/airports-of-the-world
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - node/install-packages:
          pkg-manager: yarn
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          command: yarn run lint
          name: Linting
      - run:
          command: yarn run test:cov
          name: Unit testing
      - store_artifacts:
          path: ~/airports-of-the-world/coverage
      - run:
          command: "yarn run test:e2e"
          name: E2E testing
workflows:
  test_and_deploy:
    jobs:
      - test
      - heroku/deploy-via-git:
          requires:
            - test
