version: 2.1
orbs:
  node: circleci/node@4.0.1
  heroku: circleci/heroku@1.0.1
jobs:
  set_environment:
    steps:
      - checkout
      - node/install-packages:
            pkg-manager: yarn
  unit_test:
    steps:
      - run:
          command: yarn run test
          name: Run unit tests with YARN
  e2e_test:
    steps:
      - run:
          command: yarn run test:e2e
          name: Run E2E tests with YARN
workflows:
  test_and_deploy:
    jobs:
      - set_environment
      - unit_test
      - e2e_test
